# Generated by Django 5.0.2 on 2024-04-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Regilstro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=75, verbose_name='Dependencia')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'db_table': 'dependencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dev_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_type', models.CharField(max_length=50, verbose_name='Tipo de Dispositivo')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Regilstro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo',
                'verbose_name_plural': 'Tipos de Dispositivo',
                'db_table': 'tipo_de_dispositivo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edifice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edifice', models.CharField(max_length=50, verbose_name='Edificio')),
                ('address', models.TextField(verbose_name='Domicilio')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'db_table': 'edificios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=75, verbose_name='Apellido')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'db_table': 'tecnico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='Nombre del Empleado')),
                ('employee_last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cuil', models.CharField(max_length=11, verbose_name='cuil')),
                ('status', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('JUBILACION EN TRAMITE', 'JUBILACION EN TRAMITE'), ('LICENCIA POR MATERNIDAD', 'LICENCIA POR MATERNIDAD'), ('BAJA O RETIRADO', 'BAJA O RETIRADO'), ('LICENCIA POR LARGO TRATAMIENTO', 'LICENCIA POR LARGO TRATAMIENTO')], default='ACTIVO', max_length=30, verbose_name='Estado')),
                ('user_pc', models.CharField(max_length=11, verbose_name='Nombre de Usuario')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='img_avatars/%Y/%m/%d', verbose_name='Avatar')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_dependency', to='sh.dependency', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_models/%Y/%m/%d', verbose_name='Imagen')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_brand', to='sh.brand')),
                ('dev_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_dev_type', to='sh.dev_type', verbose_name='Tipo de Dispositivo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImgPrinterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Direccion Ip')),
                ('last_review', models.DateField(verbose_name='Última Revision')),
                ('connection_type', models.CharField(choices=[('USB', 'USB'), ('RED', 'RED')], default='RED', max_length=3, verbose_name='Tipo de Conexion')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_printer_employee', to='sh.employee', verbose_name='Empleado')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_printer_model', to='sh.model', verbose_name='Modelo')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_printer_tech', to='sh.techs', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Impresor y Scanner',
                'verbose_name_plural': 'Impresoras y Scanners',
                'db_table': 'impresoras_scanners',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('JUJUY', 'JUJUY'), ('SALTA', 'SALTA')], default='SALTA', max_length=50, verbose_name='Provincia')),
                ('city', models.CharField(choices=[('SALTA CAPITAL', 'SALTA CAPITAL'), ('SAN RAMON DE LA NUEVA ORAN', 'SAN RAMON DE LA NUEVA ORAN'), ('TARTAGAL', 'TARTAGAL'), ('SAN SALVADOR DE JUJUY', 'SAN SALVADOR DE JUJUY')], default='SALTA CAPITAL', max_length=50, verbose_name='Localidad')),
                ('office', models.CharField(max_length=50, verbose_name='Oficina')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_dependency', to='sh.dependency', verbose_name='Dependencia')),
                ('edifice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_edifice', to='sh.edifice', verbose_name='Edificio')),
            ],
            options={
                'verbose_name': 'Officina',
                'verbose_name_plural': 'Oficinas',
                'db_table': 'oficina',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_office', to='sh.office', verbose_name='Oficina'),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='Direccion Ip')),
                ('pc_net_name', models.CharField(max_length=11, verbose_name='Nombre de Equipo en la Red')),
                ('last_review', models.DateField(verbose_name='Última Revision')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_employee', to='sh.employee', verbose_name='Empleado')),
                ('printer', models.ManyToManyField(related_name='computers', to='sh.imgprinterdevice', verbose_name='Impresoras')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_model', to='sh.model', verbose_name='Modelo')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_tech', to='sh.techs', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Computadora',
                'verbose_name_plural': 'Computadoras',
                'db_table': 'computadoras',
                'ordering': ['id'],
            },
        ),
    ]
