# Generated by Django 5.0.2 on 2024-02-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Regilstro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dev_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_type', models.CharField(max_length=50, verbose_name='Tipo de Dispositivo')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Regilstro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo',
                'verbose_name_plural': 'Tipos de Dispositivo',
                'db_table': 'tipo_de_dispositivo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_models/%Y/%m/%d', verbose_name='Imagen')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_brand', to='sh.brand')),
                ('dev_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_dev_type', to='sh.dev_type')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelo',
                'ordering': ['id'],
            },
        ),
    ]
