# Generated by Django 5.0.2 on 2024-02-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0002_dependency_edifice_techs_alter_model_dev_type_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='Direccion Ip')),
                ('pc_net_name', models.CharField(max_length=11, verbose_name='Nombre de Equipo en la Red')),
                ('last_review', models.DateField(verbose_name='Última Revision')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_employee', to='sh.employee', verbose_name='Empleado')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_model', to='sh.model', verbose_name='Modelo')),
                ('printer', models.ManyToManyField(related_name='computers', to='sh.imgprinterdevice', verbose_name='Impresoras')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_tech', to='sh.techs', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Computadora',
                'verbose_name_plural': 'Computadoras',
                'db_table': 'computadoras',
                'ordering': ['id'],
            },
        ),
    ]
