# Generated by Django 5.0.2 on 2024-02-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0004_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('LICENCIA POR MATERNIDAD', 'LICENCIA POR MATERNIDAD'), ('JUBILACION EN TRAMITE', 'JUBILACION EN TRAMITE'), ('ACTIVO', 'ACTIVO'), ('LICENCIA POR LARGO TRATAMIENTO', 'LICENCIA POR LARGO TRATAMIENTO'), ('BAJA O RETIRADO', 'BAJA O RETIRADO')], default='ACTIVO', max_length=30, verbose_name='Estado'),
        ),
    ]
